### ISSUE TITLE
Move Fresco into amuse.ext

### ISSUE THREAD

**Issue by rieder** [rieder/Fresco#19]
This would make sense with the upcoming modular AMUSE.

**Comment by rieder** [comment]
@ipelupessy what would be the best location to store data required for Fresco - e.g. the WFC3 PSFs etc? shared/amuse/fresco?

**Comment by ipelupessy** [comment]
that is possible.. you can also put it in a directory amuse.ext._fresco (if you have only 1 fresco.py file to put into ext) or, if you have more source files, everything together in a subdir amuse/ext/fresco

**Comment by rieder** [comment]
Maybe that's easiest.

**Comment by ipelupessy** [comment]
yea...I am not too attached to the concept of the /share/amuse/data..I think its best that every component has its data/ executables/ jars/ whatever close by...
