### ISSUE TITLE
Issue in Image-Width Indexing a ScalerQuantity

### ISSUE THREAD

**Issue by JPGlaser** [rieder/Fresco#20]
Hey @rieder , 
I am currently working on doing some visualizations and wanted to get back into using Fresco to do so (and help out by adding in a camera track option and some paralization for producing a large number of frames for movies).

I forked the lastest version and ran the test-code on the latest Python 2.7 with Amuse 12.01 installed via the old method of building.

Any ideas why this error is popping up while running the test.sh script?

~ Joe G.  

> Calculating luminosity/temperature for 100.0 Myr old stars...
> luminosities..
> ..raw images..
> Traceback (most recent call last):
>   File "../fresco.py", line 668, in <module>
>     main()
>   File "../fresco.py", line 591, in main
>     return_vmax=True,
>   File "../fresco.py", line 306, in make_image
>     return_vmax=return_vmax,
>   File "../fresco.py", line 395, in image_from_stars
>     psf_sigma=psf_sigma,
>   File "/home/jglaser/GitHub/Fresco/fresco/ubvinew.py", line 220, in rgb_frame
>     image_width=image_width,
>   File "/home/jglaser/GitHub/Fresco/fresco/gridify.py", line 14, in map_to_grid
>     return map_to_2d_grid(*args, **kwargs)
>   File "/home/jglaser/GitHub/Fresco/fresco/gridify.py", line 36, in map_to_2d_grid
>     image_width=image_width,
>   File "/home/jglaser/GitHub/Fresco/fresco/gridify.py", line 56, in map_to_2d_grid_simple
>     y_width = image_width[1]
>   File "/home/jglaser/GitHub/amuse/src/amuse/units/quantities.py", line 300, in __getitem__
>     raise exceptions.AmuseException("ScalarQuantity does not support indexing")
> amuse.support.exceptions.AmuseException: ScalarQuantity does not support indexing
>

**Comment by JPGlaser** [comment]
It looks like at some point image_width became a single value rather than a list of two values while image_size remained a list of two values. Working on a fix ...

~ Joe G.

**Comment by rieder** [comment]
Hi Joe,
Thanks for reporting. Indeed, it looks like image_width isn't used correctly in gridify.py. I've fixed that now.

**Comment by JPGlaser** [comment]
Thanks very much for that quick fix. Looks like a rebase on that last commit fixed that issue. Here are the test images that came out, which look just fine.

~ Joe G.

![test_gas-000000](https://user-images.githubusercontent.com/11276213/61478927-bc24e580-a960-11e9-8b1c-112d80caf762.png)
![test_stars-000000](https://user-images.githubusercontent.com/11276213/61478928-bc24e580-a960-11e9-8725-9c010a52f193.png)
![test_starsgas-000000](https://user-images.githubusercontent.com/11276213/61478929-bc24e580-a960-11e9-800a-c94a7685984b.png)
